'use client';

import Image from 'next/image';
import { Check } from 'lucide-react';
import { motion, useMotionValue, useSpring } from 'framer-motion';
import { SectionReveal } from './SectionReveal';

export function Experience() {
  const rotateX = useSpring(useMotionValue(0), { stiffness: 130, damping: 18 });
  const rotateY = useSpring(useMotionValue(-7), { stiffness: 130, damping: 18 });
  const onMove = (event: React.MouseEvent<HTMLDivElement>) => { const rect = event.currentTarget.getBoundingClientRect(); rotateX.set(((event.clientY - rect.top) / rect.height - .5) * -8); rotateY.set(-7 + ((event.clientX - rect.left) / rect.width - .5) * 10); };
  const reset = () => { rotateX.set(0); rotateY.set(-7); };
  return <section id="nosotros" className="py-24"><div className="shell grid items-center gap-10 lg:grid-cols-2 lg:gap-20"><SectionReveal className="relative"><div className="perspective-[1200px]" onMouseMove={onMove} onMouseLeave={reset}><motion.div style={{ rotateX, rotateY, transformStyle: 'preserve-3d' }} whileHover={{ scale: 1.025 }} className="relative"><div className="absolute inset-4 translate-x-7 translate-y-7 rounded-[2rem] bg-electric/25 blur-sm" /><div className="absolute inset-2 translate-x-4 translate-y-4 rounded-[2rem] border border-electric/35 bg-[#002b50]/70" /><div className="relative aspect-[4/4.5] overflow-hidden rounded-[2rem] border border-white/25 shadow-[22px_28px_45px_rgba(0,17,57,.35)]"><Image src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85" alt="Preparación de platos en El Pulpo Bebé" fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(135deg,rgba(0,174,239,.12),transparent_42%,rgba(0,10,45,.28))]" /></div></motion.div></div><motion.div whileHover={{ y: -4 }} className="absolute -bottom-4 -right-3 rounded-2xl border border-white/20 bg-ocean/90 p-5 shadow-xl backdrop-blur sm:-right-6"><strong className="font-display text-3xl">+12</strong><span className="ml-2 text-xs text-white/65">años compartiendo<br/>sabor y tradición</span></motion.div></SectionReveal><SectionReveal><p className="eyebrow">El Pulpo Bebé</p><h2 className="mt-3 max-w-md font-display text-4xl font-black tracking-tight sm:text-5xl">Más que comida, una experiencia.</h2><p className="mt-6 max-w-lg leading-relaxed text-white/70">Nuestra mesa reúne el sabor honesto del mar, el calor de la parrilla y esa alegría que transforma una salida en un recuerdo.</p><div className="mt-8 grid gap-3 text-sm text-white/80">{['Ingredientes frescos seleccionados cada día','Recetas con carácter y tradición marina','Un espacio para celebrar juntos'].map(x=><span className="flex items-center gap-3" key={x}><i className="grid size-5 place-items-center rounded-full bg-electric/20 text-electric"><Check size={12}/></i>{x}</span>)}</div><a href="#contacto" className="button button-outline mt-9">Conócenos mejor</a></SectionReveal></div></section>;
}
