'use client';
import Image from 'next/image';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowDownRight, Play } from 'lucide-react';
import { useEffect, useState } from 'react';
import { OceanBubbles } from './OceanBubbles';
const heroPhotos=[
  {src:'/images/hero-restaurant-premium.png',alt:'Restaurante marino premium con comensales'},
  {src:'/images/hero-restaurant-grill.png',alt:'Cocina a la parrilla de un restaurante marino premium'},
  {src:'/images/hero-seafood-dining.png',alt:'Experiencia gastronómica marina premium'},
];
export function Hero(){const reduced=useReducedMotion();const [active,setActive]=useState(0);const item={hidden:{opacity:0,y:22},show:{opacity:1,y:0}};useEffect(()=>{if(reduced)return;const timer=window.setInterval(()=>setActive(current=>(current+1)%heroPhotos.length),6500);return()=>clearInterval(timer)},[reduced]);return <section id="inicio" className="relative isolate flex min-h-[100svh] items-end overflow-hidden pb-16 pt-28 md:items-center md:pb-0">{heroPhotos.map((photo,index)=><motion.div key={photo.src} className="absolute inset-0 -z-20" initial={false} animate={{opacity:active===index?1:0,scale:active===index?1:1.04}} transition={{opacity:{duration:1.25},scale:{duration:6.5}}}><Image src={photo.src} alt={photo.alt} fill priority={index===0} sizes="100vw" className="object-cover object-center"/></motion.div>)}<div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(0,20,66,.92)_0%,rgba(0,29,78,.62)_45%,rgba(0,31,76,.22)_100%),linear-gradient(0deg,rgba(0,20,66,.8),transparent_50%)]"/><OceanBubbles count={8}/><div className="shell"><motion.div initial="hidden" animate="show" variants={{show:{transition:{staggerChildren:.12,delayChildren:.22}}}} className="max-w-2xl"><motion.p variants={item} className="eyebrow">Sabores del Callao</motion.p><motion.h1 variants={item} className="mt-5 max-w-xl font-display text-5xl font-black leading-[.93] tracking-[-.065em] sm:text-7xl">Una experiencia marina que tienes que probar.</motion.h1><motion.p variants={item} className="mt-6 max-w-lg text-base leading-relaxed text-white/75 sm:text-lg">Pescados, mariscos, parrillas y mucho más preparados para disfrutar en cada visita.</motion.p><motion.div variants={item} className="mt-9 flex flex-wrap gap-3"><a className="button button-primary" href="/carta">Ver nuestra carta <ArrowDownRight size={17}/></a><a className="button button-outline" href="#contacto">Reservar mesa</a></motion.div></motion.div><div className="absolute bottom-7 left-1/2 flex -translate-x-1/2 gap-2">{heroPhotos.map((_,index)=><button key={index} aria-label={`Ver imagen ${index+1}`} onClick={()=>setActive(index)} className={`h-1 rounded-full transition-all ${active===index?'w-7 bg-white':'w-2 bg-white/45'}`}/>)}</div><motion.div animate={reduced?{}:{y:[0,9,0]}} transition={{repeat:Infinity,duration:2.8}} className="absolute bottom-6 right-6 hidden items-center gap-2 text-xs text-white/55 md:flex"><span className="grid size-8 place-items-center rounded-full border border-white/25"><Play size={12} fill="currentColor"/></span> Puerto del Callao</motion.div></div></section>}
